### ISSUE TITLE
error

### ISSUE THREAD

**Issue by FMartinho89** [jaseg/kimesh#1]
In Kicad 7, when you run your program and generate the mesh
Gives the following error:
Traceback (most recent call last):
  File Documentos/KiCad/7.0/scripting\plugins\kimesh\mesh_dialog.py", line 208, in generate_mesh
    self.board.GetBoardPolygonOutlines(outlines, "")
  File "C:\Program Files\KiCad\7.0\bin\Lib\site-packages\pcbnew.py", line 17584, in GetBoardPolygonOutlines
    return _pcbnew.BOARD_GetBoardPolygonOutlines(self, aOutlines, aErrorHandler)
TypeError: in method 'BOARD_GetBoardPolygonOutlines', argument 3 of type 'OUTLINE_ERROR_HANDLER *'
Additional information:
Wrong number or type of arguments for overloaded function 'BOARD_GetBoardPolygonOutlines'.
  Possible C/C++ prototypes are:
    BOARD::GetBoardPolygonOutlines(SHAPE_POLY_SET &,OUTLINE_ERROR_HANDLER *)
    BOARD::GetBoardPolygonOutlines(SHAPE_POLY_SET &)

**Comment by jaseg** [comment]
I'll have a look later this week. In the meantime, you can try a KiCad nightly. I developed this on KiCad nightly, and I last ran it without problems a few weeks ago.

**Comment by jaseg** [comment]
It looks to me like that fixed your issue. If you have any other problems, feel free to open a new issue.
