### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/tmp\\dbg_grid.svg' during generation

### ISSUE THREAD

**Issue by CHENCHETY-ABHISHEK** [jaseg/kimesh#3]
I am facing below issue while using the Kimesh plugin 

```
Traceback (most recent call last):
  File "C:\Program Files\KiCad\7.99\share\kicad\scripting\plugins\kimesh\mesh_dialog.py", line 225, in generate_mesh
    self.generate_mesh_backend(mask, anchor, net_prefix=str(self.m_net_prefix.Value), target_layer_id=target_layer_id, warn=warn, settings=settings)
  File "C:\Program Files\KiCad\7.99\share\kicad\scripting\plugins\kimesh\mesh_dialog.py", line 299, in generate_mesh_backend
    with DebugOutput('dbg_grid.svg') as dbg:
  File "C:\Program Files\KiCad\7.99\bin\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Program Files\KiCad\7.99\share\kicad\scripting\plugins\kimesh\mesh_dialog.py", line 602, in DebugOutput
    with open(filename, 'w') as f:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp\\dbg_grid.svg'
```
Below is the KiCAD version info 
Application: KiCad x64 on x64

Version: 7.99.0-3095-gbf29b25190, release build

Libraries:
	wxWidgets 3.2.2
	FreeType 2.12.1
	HarfBuzz 8.0.0
	FontConfig 2.14.2
	libcurl/8.2.1-DEV Schannel zlib/1.2.13

Platform: Windows 11 (build 22621), 64-bit edition, 64 bit, Little endian, wxMSW

Build Info:
	Date: Oct  6 2023 07:18:14
	wxWidgets: 3.2.2 (wchar_t,wx containers)
	Boost: 1.82.0
	OCC: 7.7.1
	Curl: 8.2.1-DEV
	ngspice: 41
	Compiler: Visual C++ 1936 without C++ ABI

Build settings:

**Comment by CHENCHETY-ABHISHEK** [comment]
![image](https://github.com/jaseg/kimesh/assets/88726684/99cc12a5-a2da-4aac-bdbf-9a8c1d7de2ac)

After multiple hit and trails above error is shown

**Comment by jaseg** [comment]
Hi there,

you initial problem was caused by Windows. I've just commited a fix to the `main` branch that should resolve this issue on Windows.

Your second error looks weird. Perhaps try un-doing whatever you did there.

Cheers,
Jan
